[project]
name = "mcp-weather-service"
version = "0.1.0"
description = "An MCP server that fetches weather alerts and forecast data from the National Weather Service."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]
